#!/usr/bin/env bash

delete_file='rm /var/run/myscript.pid; exit $?'

echo $$ > "/var/run/myscript.pid"
trap 'echo "I hate the kill command"; '"$delete_file" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap ''"$delete_file" SIGQUIT

while 'true'
do
    echo "To infinity and beyond"
done
