#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop
# The script displays "hi" after the 9th iteration

count=0
while [ $count -lt 10 ]
do
    echo "Best School"
    (( count++ ))
if [ $count -eq 9 ]
then
    echo "Hi"
else
    continue
fi
done
