#!/usr/bin/env bash
# This script loops from 1-10
# displays "bad luck" for the 4th loop iteration;
#+ displays "good luck" for the 8th loop iteration; and
#+ displays "Best School" for the other iterations

count=1
while [ $count -le 10 ]
do
    echo "Best School"
    (( count++ ))
if [ $count -eq 4 ]
then
    echo "bad luck"
    (( count++ ))
elif [ $count -eq 8 ]
then
    echo "good luck"
    (( count++ ))
else
    continue
fi
done
