#!/usr/bin/env bash
# This script is displaying numbers from 1-20 using while loop
# The script displays "bad luck from China" after the 4th iteration,
#+ "bad luck from Japan" after the 9th iteration, and
#+ "bad luck from Italy" after the 17th iteration,

count=1
while [ $count -le 20 ]
do
    echo $count
    (( count++ ))
if [ $count -eq 5 ]
then
    echo "bad luck from China"
elif [ $count -eq 10 ]
then
    echo "bad luck from Japan"
elif [ $count -eq 18 ]
then
    echo "bad luck from Italy"
else
    continue
fi
done
