#!/usr/bin/env bash
# This script is displaying numbers from 1-20 using while loop
# The script displays "bad luck from China" after the 4th iteration,
#+ "bad luck from Japan" after the 9th iteration, and
#+ "bad luck from Italy" after the 17th iteration,

count=1
while [ $count -le 20 ]
do
    echo $count
case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
