#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# It displays hours from 0 to 12, and
#+ minutes from 1 to 59

hour=0
while [ $hour -le 12 ]
do
    echo "Hour:" $hour
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo $minutes
        (( minutes++ ))
    done
    (( hour++ ))
done
